### ISSUE TITLE
add support for generic websites

### ISSUE THREAD

**Issue by shawshankkumar** [steven-tey/og#4]
Hi!

I have a blog, blogs.shawshankkumar.me and I thought what we add support for using og.cool for all websites.
If someone uses the listed publications, we can show them the current ones.
If someone uses a generic blog and it has an og image and an og title, we can show it in an edited way.
If someone uses a link without og image/title, we can just show a default image.

Would love to hear thoughts on this and if @steven-tey and others like it, I can try to make a draft pr!

**Comment by steven-tey** [comment]
@shawshankkumar thanks for the suggestion! The main idea is to keep this as a template and allow folks to copy & paste the code (a la @shadcn-ui/ui) and host it on their own sites, so probably won't be doing this for now :)
